name: Deploy to cluster
on:
  workflow_run:
    workflows: ["golang CI workflow"]
    branches: [dev]
    types: 
      - completed
  #workflow_dispatch:
  #  inputs:
  #    comitterName:
  #      description: 'Commit author'     
  #      required: true
  #      #default: 'Repo owner'
  #    comitterMail:
  #      description: 'Commit author email'     
  #      required: true
  #      #default: 'Repo owner'
jobs:
  merge-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set Git config
        run: |
          git config --local user.email "git@github.com"
          git config --local user.name "github action"
      - name: Merge to main branch to trigger CD workflow
        run: |
          git checkout main
          git merge --no-ff dev -m "Auto-merge dev to main"